<a href="https://colab.research.google.com/github/19k41a05g6/NLP/blob/main/Assignment1_5g6.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

*Assignment*-1
 
19K41A05G6 - TEAM 14
3. Find stem and lemma words

In [ ]:
import nltk
from nltk.stem import PorterStemmer, WordNetLemmatizer
nltk.download('wordnet')
nltk.download('omw-1.4')

In [43]:
list1 = ['cats','trouble','troubling','troubled','having','Corriendo','at','was']

# stemming
porter = PorterStemmer()
print("Stem Words: ")
for words in list1:
  stemword = porter.stem(words)
  print(stemword)

Stem Words:
cat
troubl
troubl
troubl
have
corriendo
at
wa

In [44]:
# lemmatization
lemma = WordNetLemmatizer()
print("Lemma Words: ")
for words in list1:
  lemma_word = lemma.lemmatize(words)
  print(lemma_word)

Lemma Words:
cat
trouble
troubling
troubled
having
Corriendo
at
wa

  8.Find BoW for the paragraph and also find stem and lemma words

In [ ]:
from sklearn.feature_extraction.text import CountVectorizer
import pandas as pd

In [ ]:
paragraph = "Text Summarization is one of those applications of Natural Language Processing (NLP) which is bound to have a huge impact on our lives. With growing digital media and ever-growing publishing – who has the time to go through entire articles / documents / books to decide whether they are useful or not? Thankfully – this technology is already here."
count_vec = CountVectorizer()
count_occurs = count_vec.fit_transform([paragraph])

In [ ]:
count_occur_df = pd.DataFrame((count, word) for word, count in zip(count_occurs.toarray().tolist()[0], count_vec.get_feature_names()))
count_occur_df.columns = ['word','count']
count_occur_df.sort_values('count', ascending = True)

/usr/local/lib/python3.7/dist-packages/sklearn/utils/deprecation.py:87: FutureWarning: Function get_feature_names is deprecated; get_feature_names is deprecated in 1.0 and will be removed in 1.2. Please use get_feature_names_out instead.
  warnings.warn(msg, category=FutureWarning)

             word  count
0         already      1
25            not      1
27             on      1
28            one      1
29             or      1
30            our      1
31     processing      1
32     publishing      1
33  summarization      1
34     technology      1
47            who      1
35           text      1
37            the      1
38           they      1
39           this      1
40          those      1
41        through      1
42           time      1
44         useful      1
45        whether      1
46          which      1
36     thankfully      1
23        natural      1
24            nlp      1
21          lives      1
1             and      1
2    applications      1
3             are      1
4        articles      1
5           books      1
6           bound      1
7          decide      1
8         digital      1
9       documents      1
22          media      1
10         entire      1
12             go      1
14            has      1
15           have      1
16           here      1
17           huge      1
18         impact      1
20       language      1
11           ever      1
48           with      1
13        growing      2
26             of      2
43             to      3
19             is      3